#ifndef GPU_AC_KERNEL_H
#define GPU_AC_KERNEL_H

static const char *gpu_kernel_src =

/* Constants section */
"#define GPU_MATCH_CHAR        0x0000\n"
"#define GPU_MATCH_IGNORE      0x0200\n"
"#define GPU_MATCH_NOCASE      0x0400\n"
"#define GPU_MATCH_NIBBLE_HIGH 0x0100\n"
"#define GPU_MATCH_NIBBLE_LOW  0x0300\n"
"#define GPU_MATCH_METADATA    0xFF00\n"
"#define CLI_MATCH_METADATA    0xFF00\n"
"#define CLI_MATCH_CHAR        0x0000\n"
"#define CLI_MATCH_IGNORE      0x0200\n"
"#define CLI_MATCH_NOCASE      0x0400\n"
"#define CLI_MATCH_NIBBLE_HIGH 0x0100\n"
"#define CLI_MATCH_NIBBLE_LOW  0x0300\n"
"#define CLI_MATCH_SPECIAL     0x8000\n"
"\n"
"#define GPU_OFF_ANY      0\n"
"#define GPU_OFF_ABSOLUTE 1\n"
"#define GPU_OFF_NONE     0xFFFFFFFF\n"
"#define GPU_MAX_PARTS    16\n"
"\n"
"#define GPU_RESULT_CLEAN  0\n"
"#define GPU_RESULT_VIRUS  1\n"
"#define GPU_RESULT_BREAK  2\n"
"\n"


 
 

/* Logical signature bytecode opcodes */
"#define OP_LOAD_SUBSIG  0\n"  /* Load boolean (count>0) */
"#define OP_AND          1\n"
"#define OP_OR           2\n"
"#define OP_NOT          3\n"
"#define OP_END          4\n"
"\n"
/* New opcodes for count operations */
"#define OP_LOAD_COUNT   5\n"  /* Push actual count onto stack */
"#define OP_LOAD_MASK    6\n"  /* Push bitmask onto stack */
"#define OP_GT           7\n"  /* Compare count > value */
"#define OP_LT           8\n"  /* Compare count < value */
"#define OP_EQ           9\n"  /* Compare count == value */
"#define OP_COMBINE_AND  10\n" /* Combine two blocks with AND */
"#define OP_COMBINE_OR   11\n" /* Combine two blocks with OR */
"#define OP_COMBINE_NOT  12\n" /* NOT operation on block */
"#define OP_BLOCK_END    13\n" /* End of block, apply modifiers */
"\n"
/* Pattern metadata */
"typedef struct {\n"
"    uint   length;\n"
"    uint   prefix_length;\n"
"    uint   parts;\n"
"    uint   type;\n"
"    uint   sigid;\n"
"    uint   partno;\n"
"    uint   offset_min;\n"
"    uint   offset_max;\n"
"    uint   offdata0;\n"
"    uint   lsigid[3];\n"
"    uint   ch0;\n"
"    uint   ch1;\n"
"    uint   ch_mindist0;\n"
"    uint   ch_mindist1;\n"
"    uint   ch_maxdist0;\n"
"    uint   ch_maxdist1;\n"
"    uint   mindist;\n"
"    uint   maxdist;\n"
"    uint   pattern_offset;\n"
"    uint   prefix_offset;\n"
"    uint   virname_offset;\n"
"    uint   virname_len;\n"
"    uint   depth;\n"
"    uint boundary;\n"    
"    uint sigopts; \n" 
"    uint   has_regex;\n"
"    uint is_bytecode; \n" 
"} gpu_pattern_t;\n"
"\n"

/* Multi-part tracker */
"typedef struct {\n"
"    uint   sig_id;\n"
"    uint   tracker_type;  /* 0 = multi-part, 1 = logical */\n"
"    uint   total_parts;\n"
"    uint   found_mask_lo;\n"
"    uint   found_mask_hi;\n"
"    uint   offsets[GPU_MAX_PARTS][33];  /* Store up to 33 offsets per part */\n"
"    uint   offset_counts[GPU_MAX_PARTS];\n"
"    uint   first_part_realoffs[33];      /* Store realoff for first part */\n"
"    uint   last_offsets[GPU_MAX_PARTS];  /* Track last valid offset for ordering */\n"
"    uint   subsig_counts[GPU_MAX_PARTS]; /* Count matches per subsig (like lsigcnt) */\n"
"    uint   subsig_first_offset[GPU_MAX_PARTS]; /* Like lsigsuboff_first */\n"
"    uint   subsig_last_offset[GPU_MAX_PARTS];  /* Like lsigsuboff_last */\n"
"} gpu_multipart_tracker_t;\n"

/* Logical signature metadata */
"typedef struct {\n"
"    uint   sig_id;\n"
"    uint   num_subsigs;\n"
"    uint   expr_offset;\n"
"    uint   expr_length;\n"
"    uint   virname_offset;\n"
"    uint   virname_len;\n"
"    uint   tdb_container;\n"
"    uint   tdb_filesize_min;\n"
"    uint   tdb_filesize_max;\n"
"    uint   tdb_ep_min;\n"
"    uint   tdb_ep_max;\n"
"    uint   tdb_nos_min;\n"
"    uint   tdb_nos_max;\n"
"    uint   tdb_intermediates_mask;\n"
"    uint   tdb_handlertype;\n"
"    uint   tdb_icongrp1_offset;\n"
"    uint   tdb_icongrp2_offset;\n"
"    uint   bc_idx;\n"
"    uint   has_regex;\n"
"} gpu_lsig_meta_t;\n"

/* Expression instruction */
"typedef struct {\n"
"    uint   op;\n"
"    uint   operand;\n"
"} gpu_expr_inst_t;\n"
"\n"

/* Scan result */
"typedef struct {\n"
"    int    result_code;\n"
"    uint   virname_offset;\n"
"    uint   virname_len;\n"
"    uint   match_offset;\n"
"    uint   needs_cpu_fallback;\n"
"    uint   fallback_offset;\n"
"    uint   fallback_pattern_id;\n"
"} gpu_scan_result_t;\n"
"\n"


/* Helper functions */
"bool match_byte(ushort pw, uchar bb) {\n"
"    ushort wc = pw & GPU_MATCH_METADATA;\n"
"    uchar pb = (uchar)(pw & 0xFF);\n"
"    if (wc == GPU_MATCH_CHAR)    { return pb == bb; }\n"
"    if (wc == GPU_MATCH_IGNORE)  { return true; }\n"
"    if (wc == GPU_MATCH_NOCASE) {\n"
"        uchar lb = bb;\n"
"        if (lb >= 'A' && lb <= 'Z') { lb += 32; }\n"
"        uchar lp = pb;\n"
"        if (lp >= 'A' && lp <= 'Z') { lp += 32; }\n"
"        return lp == lb;\n"
"    }\n"
"    if (wc == GPU_MATCH_NIBBLE_HIGH) { return (pb & 0xF0) == (bb & 0xF0); }\n"
"    if (wc == GPU_MATCH_NIBBLE_LOW)  { return (pb & 0x0F) == (bb & 0x0F); }\n"
"    return false;\n"
"}\n"
"\n"

"bool verify_pattern(\n"
"    __global const gpu_pattern_t *patt,\n"
"    __global const ushort *pattern_bytes,\n"
"    __global const ushort *prefix_bytes,\n"
"    __global const uchar *buffer,\n"
"    uint abs_match_start,\n"
"    uint abs_end,\n"
"    uint num_pattern_bytes,\n"
"    uint num_prefix_bytes)\n"
"{\n"
"    ushort meta;\n"
"    uchar pat_byte;\n"
"    uchar buf_byte;\n"
"    \n"
"    if (patt->prefix_length > 0) {\n"
"        if (patt->prefix_offset + patt->prefix_length > num_prefix_bytes) return false;\n"
"        if (abs_match_start < patt->prefix_length) return false;\n"
"        \n"
"        uint buf_pos = abs_match_start - patt->prefix_length;\n"
"        uint pat_pos = patt->prefix_offset;\n"
"        \n"
"        for (uint j = 0; j < patt->prefix_length; j++) {\n"
"            if (buf_pos + j >= abs_end) return false;\n"
"            \n"
"            ushort pw = prefix_bytes[pat_pos + j];\n"
"            uchar pb = buffer[buf_pos + j];\n"
"            \n"
"            meta = pw & CLI_MATCH_METADATA;  /* 0xFF00 */\n"
"            pat_byte = (uchar)(pw & 0xFF);\n"
"            \n"
"            /* Handle all pattern types like CPU's AC_MATCH_CHAR macro */\n"
"            if (meta == CLI_MATCH_CHAR) {\n"
"                if (pat_byte != pb) return false;\n"
"            }\n"
"            else if (meta == CLI_MATCH_IGNORE) {\n"
"                /* Always matches - do nothing */\n"
"                continue;\n"
"            }\n"
"            else if (meta == CLI_MATCH_NOCASE) {\n"
"                uchar pb_lower = pb;\n"
"                uchar pat_lower = pat_byte;\n"
"                if (pb_lower >= 'A' && pb_lower <= 'Z') pb_lower += 32;\n"
"                if (pat_lower >= 'A' && pat_lower <= 'Z') pat_lower += 32;\n"
"                if (pat_lower != pb_lower) return false;\n"
"            }\n"
"            else if (meta == CLI_MATCH_NIBBLE_HIGH) {\n"
"                if ((pat_byte & 0xF0) != (pb & 0xF0)) return false;\n"
"            }\n"
"            else if (meta == CLI_MATCH_NIBBLE_LOW) {\n"
"                if ((pat_byte & 0x0F) != (pb & 0x0F)) return false;\n"
"            }\n"
"            else {\n"
"                /* CLI_MATCH_SPECIAL or other - can't handle on GPU */\n"
"                return false;\n"
"            }\n"
"        }\n"
"    }\n"
"    \n"
"    /* Check pattern body (forward matching like CPU) */\n"
"    uint pat_pos = patt->pattern_offset;\n"
"    for (uint j = 0; j < patt->length; j++) {\n"
"        if (abs_match_start + j >= abs_end) return false;\n"
"        \n"
"        ushort pw = pattern_bytes[pat_pos + j];\n"
"        uchar pb = buffer[abs_match_start + j];\n"
"        \n"
"        meta = pw & CLI_MATCH_METADATA;  /* 0xFF00 */\n"
"        pat_byte = (uchar)(pw & 0xFF);\n"
"        \n"
"        /* Handle all pattern types like CPU's AC_MATCH_CHAR macro */\n"
"        if (meta == CLI_MATCH_CHAR) {\n"
"            if (pat_byte != pb) return false;\n"
"        }\n"
"        else if (meta == CLI_MATCH_IGNORE) {\n"
"            /* Always matches - do nothing */\n"
"            continue;\n"
"        }\n"
"        else if (meta == CLI_MATCH_NOCASE) {\n"
"            uchar pb_lower = pb;\n"
"            uchar pat_lower = pat_byte;\n"
"            if (pb_lower >= 'A' && pb_lower <= 'Z') pb_lower += 32;\n"
"            if (pat_lower >= 'A' && pat_lower <= 'Z') pat_lower += 32;\n"
"            if (pat_lower != pb_lower) return false;\n"
"        }\n"
"        else if (meta == CLI_MATCH_NIBBLE_HIGH) {\n"
"            if ((pat_byte & 0xF0) != (pb & 0xF0)) return false;\n"
"        }\n"
"        else if (meta == CLI_MATCH_NIBBLE_LOW) {\n"
"            if ((pat_byte & 0x0F) != (pb & 0x0F)) return false;\n"
"        }\n"
"        else {\n"
"            /* CLI_MATCH_SPECIAL or other - can't handle on GPU */\n"
"            return false;\n"
"        }\n"
"    }\n"
"    \n"
"    return true;\n"
"}\n"


"bool validate_ch(\n"
"    __global const gpu_pattern_t *patt,\n"
"    __global const uchar *buffer,\n"
"    uint abs_match_start,\n"
"    uint abs_match_end,\n"
"    uint abs_file_start,\n"
"    uint abs_end)\n"
"{\n"
"    /* ch[0] - must find exactly one match within range */\n"
"    if ((patt->ch0 & GPU_MATCH_METADATA) != GPU_MATCH_IGNORE) {\n"
"        uint min_d = patt->ch_mindist0;\n"
"        uint max_d = patt->ch_maxdist0;\n"
"        if (max_d > 4096) max_d = 4096;\n"
"        \n"
"        bool found = false;\n"
"        for (uint d = min_d; d <= max_d; d++) {\n"
"            if (abs_match_start < abs_file_start + d + 1) continue;\n"
"            uint bp = abs_match_start - d - 1;\n"
"            if (bp < abs_file_start) continue;\n"
"            if (match_byte(patt->ch0, buffer[bp])) {\n"
"                found = true;\n"
"                break;  // Just break, don't check for multiple\n"
"            }\n"
"        }\n"
"        if (!found) return false;\n"
"    }\n"
"    \n"
"    /* ch[1] - must find exactly one match within range */\n"
"    if ((patt->ch1 & GPU_MATCH_METADATA) != GPU_MATCH_IGNORE) {\n"
"        uint min_d = patt->ch_mindist1;\n"
"        uint max_d = patt->ch_maxdist1;\n"
"        if (max_d > 4096) max_d = 4096;\n"
"        \n"
"        bool found = false;\n"
"        for (uint d = min_d; d <= max_d; d++) {\n"
"            uint bp = abs_match_end + 1 + d;\n"
"            if (bp >= abs_end) break;\n"
"            if (match_byte(patt->ch1, buffer[bp])) {\n"
"                found = true;\n"
"                break;\n"
"            }\n"
"        }\n"
"        if (!found) return false;\n"
"    }\n"
"    return true;\n"
"}\n"
"\n"
"\n"

/* Find or create multi-part tracker */
"__global gpu_multipart_tracker_t* find_or_create_multipart(\n"
"    __global gpu_multipart_tracker_t *pool,\n"
"    volatile __global uint *pool_count,\n"
"    uint max_pool,\n"
"    uint sig_id,\n"
"    uint total_parts,\n"
"    uint tracker_type)  /* NEW: 0 = multi-part, 1 = logical */\n"
"{\n"
"    uint n = *pool_count;\n"
"    if (n > max_pool) n = max_pool;\n"
"    /* Use both sig_id and tracker_type as key */\n"
"    uint combined_key = (sig_id << 1) | tracker_type;\n"
"    for (uint i = 0; i < n; i++) {\n"
"        uint pool_key = (pool[i].sig_id << 1) | pool[i].tracker_type;\n"
"        if (pool_key == combined_key) return &pool[i];\n"
"    }\n"
"    uint idx = atomic_inc(pool_count);\n"
"    if (idx >= max_pool) return 0;\n"
"    pool[idx].sig_id = sig_id;\n"
"    pool[idx].tracker_type = tracker_type;\n"
"    pool[idx].total_parts = total_parts;\n"
"    pool[idx].found_mask_lo = 0;\n"
"    pool[idx].found_mask_hi = 0;\n"
"    for (int i = 0; i < GPU_MAX_PARTS; i++) {\n"
"        pool[idx].offset_counts[i] = 0;\n"
"        pool[idx].subsig_counts[i] = 0;\n"
"        pool[idx].subsig_first_offset[i] = 0;\n"
"        pool[idx].subsig_last_offset[i] = 0;\n"
"        pool[idx].last_offsets[i] = 0;\n"
"    }\n"
"    return &pool[idx];\n"
"}\n"
"\n"

/* Boundary table - matches CPU version */
/* Boundary table - matches CPU version */
"__constant uchar boundary_table[256] = {\n"
"    0,0,0,0,0,0,0,0,0,0,2,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,\n"
"    3,0,2,0,0,0,0,2,0,0,0,0,0,3,1,3,0,0,0,0,0,0,0,0,0,0,0,0,1,2,2,0,\n"
"    1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,\n"
"    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,\n"
"    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,\n"
"    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,\n"
"    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,\n"
"    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"
"};\n"
"\n"

/* Helper for isalnum */
"bool is_alnum(uchar c) {\n"
"    return (c >= '0' && c <= '9') ||\n"
"           (c >= 'A' && c <= 'Z') ||\n"
"           (c >= 'a' && c <= 'z');\n"
"}\n"
"\n"

/* Match a single pattern byte against buffer byte with all special handling */
"bool match_pattern_byte(ushort pw, uchar pb) {\n"
"    ushort meta = pw & 0xFF00;\n"
"    uchar pat_byte = (uchar)(pw & 0xFF);\n"
"    \n"
"    if (meta == GPU_MATCH_CHAR) {\n"
"        return pat_byte == pb;\n"
"    }\n"
"    else if (meta == GPU_MATCH_IGNORE) {\n"
"        return true;\n"
"    }\n"
"    else if (meta == GPU_MATCH_NOCASE) {\n"
"        uchar pb_lower = pb;\n"
"        uchar pat_lower = pat_byte;\n"
"        /* Convert to lowercase only if alphabetic */\n"
"        if (pb_lower >= 'A' && pb_lower <= 'Z') pb_lower += 32;\n"
"        if (pat_lower >= 'A' && pat_lower <= 'Z') pat_lower += 32;\n"
"        return pat_lower == pb_lower;\n"
"    }\n"
"    else if (meta == GPU_MATCH_NIBBLE_HIGH) {\n"
"        return (pat_byte & 0xF0) == (pb & 0xF0);\n"
"    }\n"
"    else if (meta == GPU_MATCH_NIBBLE_LOW) {\n"
"        return (pat_byte & 0x0F) == (pb & 0x0F);\n"
"    }\n"
"    return false;\n"
"}\n"

/* Forward declaration */
"int gpu_backward_match_branch(\n"
"    __global const uchar *buffer,\n"
"    uint bp,\n"
"    uint offset,\n"
"    uint fileoffset,\n"
"    uint length,\n"
"    __global const gpu_pattern_t *patt,\n"
"    uint pp,\n"
"    __global const ushort *pattern_bytes,\n"
"    __global const ushort *prefix_bytes,\n"
"    uint *out_start,\n"
"    uint *out_end);\n"
"\n"

/* Forward matching branch - mimics CPU ac_forward_match_branch */
"int gpu_forward_match_branch(\n"
"    __global const uchar *buffer,\n"
"    uint bp,\n"
"    uint offset,\n"
"    uint fileoffset,\n"
"    uint length,\n"
"    __global const gpu_pattern_t *patt,\n"
"    uint pp,\n"
"    uint specialcnt,\n"
"    __global const ushort *pattern_bytes,\n"
"    __global const ushort *prefix_bytes,\n"
"    uint *out_start,\n"
"    uint *out_end)\n"
"{\n"
"    uint pat_pos = patt->pattern_offset + pp;\n"
"    uint buf_pos = bp;\n"
"    uint gid = get_global_id(0);\n"
"    uint match_start = offset;\n"
"    \n"
"    /* Forward pattern validation */\n"
"    for (uint i = pp; i < patt->length && buf_pos < length; i++) {\n"
"        ushort pw = pattern_bytes[pat_pos];\n"
"        uchar pb = buffer[buf_pos];\n"
"        \n"
"        if (!match_pattern_byte(pw, pb)) {\n"
"            return 0;\n"
"        }\n"
"        \n"
"        pat_pos++;\n"
"        buf_pos++;\n"
"    }\n"
"    \n"
"    *out_end = buf_pos;\n"
"    \n"
"    /* Right-side boundary checks */\n"
"    if (patt->boundary & 0x0C) {\n"
"        uint boundary_flags = patt->boundary;\n"
"        \n"
"        /* AC_BOUNDARY_RIGHT check (0x0004) */\n"
"        if (boundary_flags & 0x0004) {\n"
"            bool match = !(boundary_flags & 0x0008);\n"
"            bool boundary_cond = (buf_pos == length || boundary_table[buffer[buf_pos]] >= 2);\n"
"            if (boundary_cond) match = !match;\n"
"            if (!match) return 0;\n"
"        }\n"
"        \n"
"        /* AC_LINE_MARKER_RIGHT check (0x0040) */\n"
"        if (boundary_flags & 0x0040) {\n"
"            bool match = !(boundary_flags & 0x0080);\n"
"            bool line_cond = (buf_pos == length || \n"
"                              buffer[buf_pos] == '\\n' || \n"
"                              (buffer[buf_pos] == '\\r' && buf_pos + 1 < length && buffer[buf_pos + 1] == '\\n'));\n"
"            if (line_cond) match = !match;\n"
"            if (!match) return 0;\n"
"        }\n"
"        \n"
"        /* AC_WORD_MARKER_RIGHT check (0x0400) */\n"
"        if (boundary_flags & 0x0400) {\n"
"            bool match = !(boundary_flags & 0x0800);\n"
"            bool word_cond = (buf_pos == length || !is_alnum(buffer[buf_pos]));\n"
"            if (word_cond) match = !match;\n"
"            if (!match) return 0;\n"
"        }\n"
"    }\n"
"    \n"
"    /* ch[1] validation */\n"
"    if ((patt->ch1 & GPU_MATCH_METADATA) != GPU_MATCH_IGNORE) {\n"
"        uint min_d = patt->ch_mindist1;\n"
"        uint max_d = patt->ch_maxdist1;\n"
"        if (max_d > 4096) max_d = 4096;\n"
"        \n"
"        uint search_pos = buf_pos + min_d;\n"
"        bool found = false;\n"
"        \n"
"        for (uint d = min_d; d <= max_d && !found; d++) {\n"
"            if (search_pos >= length) break;\n"
"            if (match_pattern_byte(patt->ch1, buffer[search_pos])) {\n"
"                found = true;\n"
"                break;\n"
"            }\n"
"            search_pos++;\n"
"        }\n"
"        if (!found) return 0;\n"
"    }\n"
"    \n"
"    /* Guard against offset == 0 (can't go backwards) */\n"
"    if (match_start == 0 || patt->prefix_length == 0) {\n"
"        *out_start = match_start;\n"
"        return 1;\n"
"    }\n"
"    \n"
"    /* Now do backward matching for prefix */\n"
"    return gpu_backward_match_branch(buffer, match_start - 1, match_start, fileoffset, length,\n"
"                                      patt, patt->prefix_length - 1, \n"
"                                      pattern_bytes, prefix_bytes,\n"
"                                      out_start, out_end);\n"
"}\n"

/* Backward matching branch - mimics CPU ac_backward_match_branch with debug prints */
"int gpu_backward_match_branch(\n"
"    __global const uchar *buffer,\n"
"    uint bp,\n"
"    uint offset,\n"
"    uint fileoffset,\n"
"    uint length,\n"
"    __global const gpu_pattern_t *patt,\n"
"    uint pp,\n"
"    __global const ushort *pattern_bytes,\n"
"    __global const ushort *prefix_bytes,\n"
"    uint *out_start,\n"
"    uint *out_end)\n"
"{\n"
"    uint buf_pos = bp;\n"
"    uint gid = get_global_id(0);\n"
"    \n"
"    /* Backward prefix validation */\n"
"    if (patt->prefix_length > 0 && pp < patt->prefix_length) {\n"
"        uint pat_pos = patt->prefix_offset + pp;\n"
"        \n"
"        for (int i = pp; i >= 0; i--) {\n"
"            /* Check buffer underflow */\n"
"            if (buf_pos < fileoffset - offset) {\n"
"                return 0;\n"
"            }\n"
"            \n"
"            ushort pw = prefix_bytes[pat_pos];\n"
"            uchar pb = buffer[buf_pos];\n"
"            \n"
"            if (!match_pattern_byte(pw, pb)) {\n"
"                return 0;\n"
"            }\n"
"            \n"
"            if (i == 0 || buf_pos == 0) break;\n"
"            \n"
"            /* Safely decrement pat_pos - don't go below prefix_offset */\n"
"            if (pat_pos > patt->prefix_offset) {\n"
"                pat_pos--;\n"
"            }\n"
"            buf_pos--;\n"
"        }\n"
"        \n"
"        *out_start = buf_pos;\n"
"    } else {\n"
"        *out_start = offset;\n"
"        buf_pos = offset;\n"
"    }\n"
"    \n"
"    /* Calculate filestart safely - avoid underflow */\n"
"    uint filestart;\n"
"    if (fileoffset >= offset) {\n"
"        filestart = fileoffset - offset + *out_start;\n"
"    } else {\n"
"        filestart = *out_start;\n"
"    }\n"
"    \n"
"    /* Left-side boundary checks */\n"
"    if (patt->boundary & 0x03) {\n"
"        uint boundary_flags = patt->boundary;\n"
"        \n"
"        /* AC_BOUNDARY_LEFT check (0x0001) */\n"
"        if (boundary_flags & 0x0001) {\n"
"            bool match = !(boundary_flags & 0x0002);\n"
"            bool boundary_cond = (!filestart || \n"
"                                  (*out_start > 0 && (boundary_table[buffer[*out_start - 1]] == 1 || \n"
"                                                      boundary_table[buffer[*out_start - 1]] == 3)));\n"
"            if (boundary_cond) match = !match;\n"
"            if (!match) return 0;\n"
"        }\n"
"        \n"
"        /* AC_LINE_MARKER_LEFT check (0x0010) */\n"
"        if (boundary_flags & 0x0010) {\n"
"            bool match = !(boundary_flags & 0x0020);\n"
"            bool line_cond = (!filestart || (*out_start > 0 && buffer[*out_start - 1] == '\\n'));\n"
"            if (line_cond) match = !match;\n"
"            if (!match) return 0;\n"
"        }\n"
"        \n"
"        /* AC_WORD_MARKER_LEFT check (0x0100) */\n"
"        if (boundary_flags & 0x0100) {\n"
"            bool match = !(boundary_flags & 0x0200);\n"
"            bool word_cond = (!filestart || (*out_start > 0 && !is_alnum(buffer[*out_start - 1])));\n"
"            if (word_cond) match = !match;\n"
"            if (!match) return 0;\n"
"        }\n"
"    }\n"
"    \n"
"    /* ch[0] validation */\n"
"    if ((patt->ch0 & GPU_MATCH_METADATA) != GPU_MATCH_IGNORE) {\n"
"        uint min_d = patt->ch_mindist0;\n"
"        uint max_d = patt->ch_maxdist0;\n"
"        if (max_d > 4096) max_d = 4096;\n"
"        \n"
"        if (min_d + 1 > *out_start) return 0;\n"
"        \n"
"        uint search_pos = *out_start - min_d - 1;\n"
"        bool found = false;\n"
"        uint file_start_boundary = fileoffset - offset;\n"
"        \n"
"        for (uint d = min_d; d <= max_d && !found; d++) {\n"
"            /* Check if we've gone before the file start */\n"
"            if (search_pos < file_start_boundary) break;\n"
"            \n"
"            if (match_pattern_byte(patt->ch0, buffer[search_pos])) {\n"
"                found = true;\n"
"                break;\n"
"            }\n"
"            if (search_pos == 0) break;\n"
"            search_pos--;\n"
"        }\n"
"        if (!found) return 0;\n"
"    }\n"
"    \n"
"    return 1;\n"
"}\n"


/* Main pattern validation function with debug prints */
"bool gpu_findmatch(\n"
"    __global const uchar *buffer,\n"
"    uint offset,\n"
"    uint fileoffset,\n"
"    uint length,\n"
"    __global const gpu_pattern_t *patt,\n"
"    uint *out_start,\n"
"    uint *out_end,\n"
"    __global const ushort *pattern_bytes,\n"
"    __global const ushort *prefix_bytes)\n"
"{\n"
"    uint gid = get_global_id(0);\n"
"    \n"
"    /* Basic bounds checks */\n"
"    if (offset + patt->length > length) {\n"
// "        if (gid < 5 && patt->virname_offset != 0) {\n"
// "            printf(\"[GPU] gpu_findmatch: offset+length=%u > length=%u - OUT OF BOUNDS\\n\",\n"
// "                   offset + patt->length, length);\n"
// "        }\n"
"        return false;\n"
"    }\n"
"    if (patt->prefix_length > offset) {\n"
// "        if (gid < 5 && patt->virname_offset != 0) {\n"
// "            printf(\"[GPU] gpu_findmatch: prefix_length=%u > offset=%u - OUT OF BOUNDS\\n\",\n"
// "                   patt->prefix_length, offset);\n"
// "        }\n"
"        return false;\n"
"    }\n"
"    \n"
// "    if (gid < 5 && patt->virname_offset != 0) {\n"
// "        printf(\"[GPU] gpu_findmatch: Starting validation for sig_id=%u, offset=%u, length=%u\\n\",\n"
// "               patt->sigid, offset, patt->length);\n"
// "        printf(\"[GPU]   prefix_len=%u, depth=%u, pattern_offset=%u\\n\",\n"
// "               patt->prefix_length, patt->depth, patt->pattern_offset);\n"
// "    }\n"
"    \n"
"    /* Simple forward/backward validation */\n"
"    int result = gpu_forward_match_branch(buffer, offset + patt->depth, offset, fileoffset, length,\n"
"                                          patt, patt->depth, 0,\n"
"                                          pattern_bytes, prefix_bytes,\n"
"                                          out_start, out_end);\n"
"    \n"
// "    if (gid < 5 && patt->virname_offset != 0) {\n"
// "        if (result) {\n"
// "            printf(\"[GPU] gpu_findmatch: VALIDATION SUCCESS for sig_id=%u, out_start=%u, out_end=%u\\n\",\n"
// "                   patt->sigid, *out_start, *out_end);\n"
// "        } else {\n"
// "            printf(\"[GPU] gpu_findmatch: VALIDATION FAILED for sig_id=%u\\n\", patt->sigid);\n"
// "        }\n"
// "    }\n"
"    \n"
"    return result != 0;\n"
"}\n"
"\n"


 "bool validate_pattern_before_tracker(\n"
"    __global const uchar *file_buffer,\n"
"    uint abs_match_start,\n"
"    uint abs_file_start,\n"
"    uint abs_file_end,\n"
"    __global const gpu_pattern_t *patt,\n"
"    __global const ushort *pattern_bytes,\n"
"    __global const ushort *prefix_bytes,\n"
"    uint file_offset,\n"
"    uint *out_match_start,\n"
"    uint *out_match_end)\n"
"{\n"
"    /* Basic bounds checks */\n"
"    if (abs_match_start + patt->length > abs_file_end) return false;\n"
"    if (patt->prefix_length > abs_match_start - abs_file_start) return false;\n"
"    \n"
"    /* Check offset constraints */\n"
"    uint rel_match_start = abs_match_start - file_offset;\n"
"    if (patt->offdata0 == GPU_OFF_ABSOLUTE) {\n"
"        if (rel_match_start < patt->offset_min || \n"
"            rel_match_start > patt->offset_max) {\n"
"            return false;\n"
"        }\n"
"    }\n"
"    \n"
"    /* Validate the full pattern */\n"
"    return gpu_findmatch(file_buffer, abs_match_start, abs_file_start,\n"
"                         abs_file_end, patt, out_match_start, out_match_end,\n"
"                         pattern_bytes, prefix_bytes);\n"
"}\n"
/* MAIN SCAN KERNEL */
"__kernel void ac_scan_validate(\n"
"    __global const uchar *file_buffer,\n"
"    uint file_offset,\n"
"    uint file_length,\n"
"    __global const uint *dfa_next,\n"
"    __global const uint *dfa_out_index,\n"
"    __global const ushort *dfa_out_count,\n"
"    __global const ushort *dfa_out_pat,\n"
"    uint dfa_states,\n"
"    __global const gpu_pattern_t *patterns,\n"
"    uint num_patterns,\n"
"    __global const ushort *pattern_bytes,\n"
"    __global const ushort *prefix_bytes,\n"
"    __global gpu_multipart_tracker_t *tracker_pool,\n"
"    volatile __global uint *tracker_count,\n"
"    uint max_trackers,\n"
"    uint chunk_size,\n"
"    uint stride,\n"
"    __local uint *state0_cache,\n"
"    volatile __global gpu_scan_result_t *result,\n"
"    uint num_pattern_bytes,\n"
"    uint num_prefix_bytes,\n"
"    uint out_total,\n"
"    __global const gpu_lsig_meta_t *lsig_metas,\n"
"    uint num_lsigs,\n"
"    uint container_type,\n"
"    uint entry_point,\n"
"    uint is_pe_target,\n"
"    uint is_elf_target\n"
") {\n"

"    uint gid = get_global_id(0);\n"
"    uint lid = get_local_id(0);\n"
"    uint dbg_total_outputs = 0;\n"
"    uint dbg_lsig_skipped = 0;\n"
"    uint dbg_type_skipped = 0;\n"
"    uint dbg_depth_skipped = 0;\n"
"    uint dbg_offset_skipped = 0;\n"
"    uint dbg_verify_failed = 0;\n"
"    uint dbg_ch_failed = 0;\n"
"    uint dbg_simple_virus = 0;\n"
"    uint dbg_multipart_stored = 0;\n"
"    uint dbg_multipart_complete = 0;\n"
"\n"
// "    if (get_global_id(0) == 0) {\n"
// "        printf(\"KERNEL ENTRY: gid=0 reached start of kernel\\n\");\n"
// "        printf(\"  file_length=%u, chunk_size=%u, stride=%u\\n\", \n"
// "               file_length, chunk_size, stride);\n"
// "    }\n"
// "    if (gid == 0) {\n"
// "        printf(\"MAIN KERNEL STARTED: file_length=%u, chunk_size=%u, stride=%u\\n\",\n"
// "               file_length, chunk_size, stride);\n"
// "    }\n"
"    uint abs_file_start = file_offset;\n"
"    uint abs_file_end = file_offset + file_length;\n"
"    uint abs_start = file_offset + gid * stride;\n"
"    if (abs_start >= abs_file_end) return;\n"
"    uint abs_end = abs_start + chunk_size;\n"
"    if (abs_end > abs_file_end) abs_end = abs_file_end;\n"
"\n"
"                    if (result->result_code == GPU_RESULT_VIRUS) {\n"
"                        printf(\"[GPU] *** VIRUS DETECTED BY GPU: gid=%u, virname_offset=%u ***\\n\",\n"
"                               gid, result->virname_offset);\n"
"                    }\n"
"    if (result->result_code == GPU_RESULT_VIRUS) return;\n"
"\n"
"    if (lid < 256) state0_cache[lid] = dfa_next[lid];\n"
"    barrier(CLK_LOCAL_MEM_FENCE);\n"
"\n"
"    uint state = 0;\n"
"\n"
"    uint loop_count = 0;\n"
"    uint max_loops = (abs_end - abs_start) * 10;  /* Safety factor */\n"
"    for (uint pos = abs_start; pos < abs_end; pos++) {\n"
"        loop_count++;\n"
// "        if (loop_count > max_loops) {\n"
// "            printf(\"ERROR: Infinite loop detected at pos=%u\\n\", pos);\n"
// "            return;\n"
// "        }\n"
"        if ((pos & 0xFFF) == 0) {\n"
"                    if (result->result_code == GPU_RESULT_VIRUS) {\n"
"                        printf(\"[GPU] *** VIRUS DETECTED BY GPU: gid=%u, virname_offset=%u ***\\n\",\n"
"                               gid, result->virname_offset);\n"
"                    }\n"
"            if (result->result_code == GPU_RESULT_VIRUS) return;\n"
"        }\n"
"        uchar c = file_buffer[pos];\n"
"\n"
"        if (state == 0) {\n"
"            state = state0_cache[c];\n"
"        } else {\n"
"            if (state >= dfa_states) { state = 0; continue; }\n"
"            uint idx = state * 256 + c;\n"
"            if (idx < dfa_states * 256) state = dfa_next[idx];\n"
"            else state = 0;\n"
"        }\n"
"        if (state >= dfa_states) { state = 0; continue; }\n"
"\n"
"        ushort cnt = dfa_out_count[state];\n"
"        if (cnt == 0) continue;\n"
"        if (cnt > 64) cnt = 64;\n"
"        uint out_idx = dfa_out_index[state];\n"
"        if (out_idx >= out_total || out_idx + cnt > out_total) continue;\n"
"\n"
"        for (uint i = 0; i < cnt; i++) {\n"
"            ushort pid = dfa_out_pat[out_idx + i];\n"
// "            if (pid < 10) {  /* Check first few patterns */\n"
// "                printf(\"MAIN KERNEL: DFA OUTPUT - pid=%u at pos=%u\\n\", pid, pos);\n"
// "            }\n"
"            dbg_total_outputs++;\n"
"            if (pid >= num_patterns) continue;\n"
"\n"
"            __global const gpu_pattern_t *patt = &patterns[pid];\n"
"            /* Skip known false positive signature */\n"
"            if (patt->virname_offset == 124649) {\n"
"                continue;\n"
"            }\n"
"\n"
"            if (result->needs_cpu_fallback) {\n"
"                return;\n"
"            }\n"
"\n"
"            /* Check if this pattern belongs to a regex logical signature */\n"
"            if (patt->lsigid[0]) {\n"
"                uint lsig_idx = patt->lsigid[1] - 1;\n"
"                if (lsig_idx < num_lsigs) {\n"
"                    __global const gpu_lsig_meta_t *lsig_meta = &lsig_metas[lsig_idx];\n"
"                    \n"
"                    if (lsig_meta->tdb_container == 0) {\n"
"                        /* Check if this is a known problematic signature family */\n"
"                        if (lsig_meta->virname_offset == 124649 || /* Win.Trojan.SwizzorA-1 */\n"
"                            lsig_meta->virname_offset == 123197 || /* Win.Trojan.SkinTrim-1 */\n"
"                            lsig_meta->virname_offset == 167560) { /* Emf.Exploit.CVE_2018_4949 */\n"
"                            /* Known false positive - fall back to CPU */\n"
"                            atomic_cmpxchg(&result->needs_cpu_fallback, 0, 1);\n"
"                            return;\n"
"                        }\n"
"                        /* For other signatures without container info, trust the GPU */\n"
"                    }\n"
"                    /* For ELF files, many signatures with regex are false positives */\n"
"                    if (is_elf_target) {\n"
"                        /* If this signature has a container restriction and it's not ELF */\n"
"                        if (lsig_meta->tdb_container && \n"
"                            lsig_meta->tdb_container != container_type) {\n"
"                            /* Signature is for a different file type */\n"
"                            continue;\n"
"                        }\n"
"                        /* If signature has no container restriction, be careful */\n"
"                        if (lsig_meta->tdb_container == 0) {\n"
"                            /* No container info - could be Windows, fall back to CPU */\n"
"                            atomic_cmpxchg(&result->needs_cpu_fallback, 0, 1);\n"
"                            return;\n"
"                        }\n"
"                    }\n"
"                    \n"
// "                    if (lsig_meta->has_regex) {\n"
// "                        atomic_cmpxchg(&result->needs_cpu_fallback, 0, 1);\n"
// "                        return;\n"
// "                    }\n"
"                }\n"
"            }\n"
"\n"
"            /* File type sigs - skip */\n" 
"            if (patt->type != 0) { dbg_type_skipped++; continue; }\n"
"\n"
"            if (patt->depth == 0) { dbg_depth_skipped++; continue; }\n"
"\n"
"            uint abs_match_start = pos - patt->depth + 1;\n"
"            if (pos < patt->depth - 1) continue;\n"
"            uint abs_match_end = abs_match_start + patt->length - 1;\n"
"            if (abs_match_end >= abs_file_end) continue;\n"
"            if (abs_match_start < abs_file_start) continue;\n"
"            uint rel_match_start = abs_match_start - file_offset;\n"
"            uint rel_match_end = abs_match_end - file_offset;\n"
"\n"
"            /* Check offset constraints */\n"
"            if (patt->offdata0 == GPU_OFF_ABSOLUTE) {\n"
"                if (rel_match_start < patt->offset_min || \n"
"                    rel_match_start > patt->offset_max) {\n"
"                    continue;\n"
"                }\n"
"            }\n"
"\n"
"            /* Validate the full pattern */\n"
"            uint match_start, match_end;\n"
"            bool match_result = gpu_findmatch(file_buffer, abs_match_start, abs_file_start,\n"
"                                              abs_file_end, patt, &match_start, &match_end,\n"
"                                              pattern_bytes, prefix_bytes);\n"
"\n"
"            if (!match_result) {\n"
"                continue;  /* Pattern doesn't actually match - skip */\n"
"            }\n"
"\n"
"            /* ONLY NOW handle the validated match */\n"
"            if (patt->lsigid[0]) {\n"
"                /* Logical signature - create/update tracker */\n"
"                if (patt->parts > 0 && patt->lsigid[2] < patt->parts) {\n"
"                    __global gpu_multipart_tracker_t *trk =\n"
"                        find_or_create_multipart(\n"
"                        tracker_pool, tracker_count,\n"
"                        max_trackers, patt->lsigid[1], patt->parts, 1);\n"
"                    if (!trk) continue;\n"
"                    \n"
"                    uint subsig_idx = patt->lsigid[2];\n"
"                    atomic_inc(&trk->subsig_counts[subsig_idx]);\n"
"                    atomic_or(&trk->found_mask_lo, (1u << subsig_idx));\n"
"                    \n"
"                    /* Debug print for validation */\n"
"                    if (patt->virname_offset != 0 && get_global_id(0) < 5) {\n"
"                        printf(\"VALIDATED logical match: sig_id=%u, subsig=%u at offset=%u\\n\",\n"
"                               patt->lsigid[1], patt->lsigid[2], abs_match_start);\n"
"                    }\n"
"                }\n"
"                continue;  /* Don't process as simple pattern */\n"
"            }\n"
"\n"
"            /* Handle simple patterns (non-logical) */\n"
"            /* Handle simple single-part patterns (non-logical) */\n"
"            if (patt->sigid == 0 && patt->parts <= 1 && patt->virname_offset != 0) {\n"
"                /* Skip unknown file types */\n"
"                if (!is_pe_target && !is_elf_target && container_type == 0) {\n"
"                    continue;\n"
"                }\n"
"                \n"
"                /* Check offset constraints */\n"
"                if (patt->offdata0 == GPU_OFF_ABSOLUTE) {\n"
"                    if (rel_match_start < patt->offset_min || \n"
"                        rel_match_start > patt->offset_max) {\n"
"                        continue;\n"
"                    }\n"
"                }\n"
"                \n"
"                /* Validate the full pattern */\n"
"                uint match_start, match_end;\n"
"                bool match_result = gpu_findmatch(file_buffer, abs_match_start, abs_file_start,\n"
"                                                  abs_file_end, patt, &match_start, &match_end,\n"
"                                                  pattern_bytes, prefix_bytes);\n"
"                if (match_result) {\n"
"                    /* Only then report virus */\n"
"                    int old = atomic_cmpxchg(&result->result_code, GPU_RESULT_CLEAN, GPU_RESULT_VIRUS);\n"
"                    if (old == GPU_RESULT_CLEAN) {\n"
"                        result->virname_offset = patt->virname_offset;\n"
"                        result->virname_len = patt->virname_len;\n"
"                    }\n"
"                    return;\n"
"                }\n"
"            }\n"
"            if (patt->virname_offset == 124649) {\n"
"                /* This signature causes false positives - force CPU fallback */\n"
"                atomic_cmpxchg(&result->needs_cpu_fallback, 0, 1);\n"
"                return;\n"
"            }\n"
"            /* Multi-part signature */\n"
"            if (patt->sigid != 0 && patt->parts > 1) {\n"
"                        continue;\n"
"                if (patt->parts > GPU_MAX_PARTS) continue;\n"
"\n"
"                __global gpu_multipart_tracker_t *trk =\n"
"                find_or_create_multipart(\n"
"                tracker_pool, tracker_count,\n"
"                max_trackers, patt->sigid, patt->parts, 0);\n" 
"\n"
"                if (!trk) continue;\n"
"\n"
"                uint part = patt->partno - 1;\n"
"                if (part >= GPU_MAX_PARTS) continue;\n"
"\n"
"                /* CPU: For part 2 or later, check if previous part has matched */\n"
"                if (part > 0) {\n"
"                    if (trk->offset_counts[part - 1] == 0) {\n"
"                        /* Previous part hasn't matched yet - skip */\n"
// "                        if (gid < 5) {\n"
// "                            printf(\"SIG%u PART %u: skipped - prev part %u not matched\\n\",\n"
// "                                   patt->sigid, part, part-1);\n"
// "                        }\n"
"                        continue;\n"
"                    }\n"
"                }\n"
"\n"
"                /* CPU: Check if this offset is valid relative to previous part matches */\n"
"                int offset_valid = 1;\n"
"                if (part > 0) {\n"
"                    /* We need to find a valid sequence */\n"
"                    /* For now, just store and we'll validate at the end */\n"
"                }\n"
"\n"
"                /* Store this offset (like CPU's offmatrix) */\n"
"                uint count = trk->offset_counts[part];\n"
"                if (count < 33) {\n"
"                    trk->offsets[part][count] = rel_match_end;\n"
"                    trk->offset_counts[part] = count + 1;\n"
"                    \n"
"                    if (part == 0) {\n"
"                        /* Store realoff for first part (used for virus reporting) */\n"
"                        trk->first_part_realoffs[count] = rel_match_start;\n"
"                    }\n"
"                    \n"
// "                    if (gid < 5) {\n"
// "                        printf(\"SIG%u PART %u: stored offset %u at idx %u (total=%u)\\n\",\n"
// "                               patt->sigid, part, rel_match_end, count, count+1);\n"
// "                    }\n"
"                }\n"
"\n"
"                /* Mark this part as found in mask */\n"
"                uint mask = (1u << part);\n"
"                atomic_or(&trk->found_mask_lo, mask);\n"
"\n"
"                /* Update last offset for this part */\n"
"                trk->last_offsets[part] = rel_match_end;\n"
"\n"
"                /* Check if all parts have at least one offset */\n"
"                uint all_parts_present = 1;\n"
"                for (uint p = 0; p < patt->parts; p++) {\n"
"                    if (trk->offset_counts[p] == 0) {\n"
"                        all_parts_present = 0;\n"
"                        break;\n"
"                    }\n"
"                }\n"
"\n"
"                /* CPU: Only validate when we have the last part and all parts are present */\n"
"                if (all_parts_present && part == patt->parts - 1) {\n"
"                    if (gid < 5) {\n"
"                        printf(\"SIG%u: All %u parts present, validating sequences...\\n\",\n"
"                               patt->sigid, patt->parts);\n"
"                    }\n"
"                    \n"
"                    int found_valid = 0;\n"
"                    \n"
"                    /* Try each possible sequence starting from first part offsets */\n"
"                    for (uint i1 = 0; i1 < trk->offset_counts[0] && !found_valid; i1++) {\n"
"                        uint prev_offset = trk->offsets[0][i1];\n"
"                        uint prev_realoff = trk->first_part_realoffs[i1];\n"
"                        int sequence_valid = 1;\n"
"\n"
"                        for (uint p = 1; p < patt->parts && sequence_valid; p++) {\n"
"                            uint found = 0;\n"
"                            \n"
"                            /* Find first valid offset for this part that's > previous */\n"
"                            for (uint idx = 0; idx < trk->offset_counts[p] && !found; idx++) {\n"
"                                uint curr_offset = trk->offsets[p][idx];\n"
"                                if (curr_offset > prev_offset) {\n"
"                                    /* CPU: Check distance constraints */\n"
"                                    int dist_ok = 1;\n"
"                                    if (patt->mindist || patt->maxdist) {\n"
"                                        uint dist = curr_offset - prev_offset;\n"
"                                        if (patt->mindist && dist < patt->mindist) dist_ok = 0;\n"
"                                        if (patt->maxdist && dist > patt->maxdist) dist_ok = 0;\n"
"                                    }\n"
"                                    if (dist_ok) {\n"
"                                        prev_offset = curr_offset;\n"
"                                        found = 1;\n"
// "                                        if (gid < 5) {\n"
// "                                            printf(\"SIG%u: part %u using offset %u\\n\",\n"
// "                                                   patt->sigid, p, curr_offset);\n"
// "                                        }\n"
"                                    }\n"
"                                }\n"
"                            }\n"
"                            if (!found) {\n"
"                                sequence_valid = 0;\n"
"                                break;\n"
"                            }\n"
"                        }\n"
"\n"
"                        if (sequence_valid) {\n"
"                            found_valid = 1;\n"
"                            \n"
"                            /* CPU: Verify the full pattern matches */\n"
"                            if (!verify_pattern(patt, pattern_bytes, prefix_bytes,\n"
"                                                file_buffer, abs_match_start,\n"
"                                                abs_file_end, num_pattern_bytes,\n"
"                                                num_prefix_bytes)) {\n"
"                                if (patt->virname_offset == 66718) {\n"
"                                    printf(\"SIG%u: verify_pattern FAILED for virname_offset=66718 (good!)\\n\", patt->sigid);\n"
"                                } else if (gid < 5) {\n"
"                                    printf(\"SIG%u: pattern verification failed\\n\", patt->sigid);\n"
"                                }\n"
"                                continue;\n"
"                            }\n"
"                            \n"
"                            /* CPU: Validate ch[0]/ch[1] if present */\n"
"                            if ((patt->ch0 & GPU_MATCH_METADATA) != GPU_MATCH_IGNORE ||\n"
"                                (patt->ch1 & GPU_MATCH_METADATA) != GPU_MATCH_IGNORE) {\n"
"                                if (!validate_ch(patt, file_buffer,\n"
"                                                 abs_match_start, abs_match_end,\n"
"                                                 abs_file_start, abs_file_end)) {\n"
"                                    if (patt->virname_offset == 66718) {\n"
"                                        printf(\"SIG%u: ch validation FAILED for virname_offset=66718 (good!)\\n\", patt->sigid);\n"
"                                    } else if (gid < 5) {\n"
"                                        printf(\"SIG%u: ch validation failed\\n\", patt->sigid);\n"
"                                    }\n"
"                                    continue;\n"
"                                }\n"
"                            }\n"
"\n"
"                            /* If we get here, all validations passed - this is a potential virus */\n"
"                            if (patt->virname_offset == 66718) {\n"
"                                printf(\"SIG%u: *** FALSE POSITIVE CANDIDATE for virname_offset=66718 ***\\n\", patt->sigid);\n"
"                                printf(\"  abs_match_start=%u, pattern_offset=%u, length=%u, parts=%u\\n\",\n"
"                                       abs_match_start, patt->pattern_offset, patt->length, patt->parts);\n"
"                                printf(\"  first_part_realoff=%u, prev_realoff=%u\\n\", prev_realoff, prev_realoff);\n"
"                                \n"
"                                /* Dump first 16 pattern bytes */\n"
"                                printf(\"  Pattern[0-15]: \");\n"
"                                for (uint k = 0; k < 16 && k < patt->length; k++) {\n"
"                                    ushort pw = pattern_bytes[patt->pattern_offset + k];\n"
"                                    printf(\"0x%04x \", pw);\n"
"                                }\n"
"                                printf(\"\\n\");\n"
"                                \n"
"                                /* Dump first 16 buffer bytes at match start */\n"
"                                printf(\"  Buffer[%u-%u]: \", abs_match_start, abs_match_start+15);\n"
"                                for (uint k = 0; k < 16 && abs_match_start + k < abs_file_end; k++) {\n"
"                                    printf(\"0x%02x \", file_buffer[abs_match_start + k]);\n"
"                                }\n"
"                                printf(\"\\n\");\n"
"                            }\n"
"\n"
"                            /* CPU: Report virus */\n"
"                            printf(\"[GPU] MULTI-PART VIRUS: sig_id=%u, parts=%u, virname_offset=%u\\n\",\n"
"                                   patt->sigid, patt->parts, patt->virname_offset);\n"
"                            \n"
"                    int old = atomic_cmpxchg(\n"
"                        (volatile __global int*)&result->result_code,\n"
"                        GPU_RESULT_CLEAN, GPU_RESULT_VIRUS);\n"
"                            if (old == GPU_RESULT_CLEAN) {\n"
"                                result->virname_offset = patt->virname_offset;  // Use patt\n"
"                                result->virname_len = patt->virname_len;        // Use patt\n"
"                                result->match_offset = prev_realoff;\n"
"                            }\n"
"                            return;\n"
"                        }\n"
"                    }\n"
"                    \n"
"                    if (!found_valid && patt->virname_offset == 66718) {\n"
"                        printf(\"SIG%u: No valid sequence found for virname_offset=66718\\n\", patt->sigid);\n"
"                    } else if (gid < 5 && !found_valid) {\n"
"                        printf(\"SIG%u: No valid sequence found\\n\", patt->sigid);\n"
"                    }\n"
"                }\n"
"                continue;\n"
"            }\n"
"\n"
"        }\n"      // Close for i loop
"    }\n"          // Close for pos loop
"}\n"       // Close kernel function
/* LOGICAL SIGNATURE EVALUATION KERNEL */
/* LOGICAL SIGNATURE EVALUATION KERNEL */
"__kernel void evaluate_logical_sigs(\n"
"    __global const gpu_lsig_meta_t *lsig_metas,\n"
"    uint num_lsigs,\n"
"    __global const gpu_expr_inst_t *expr_bytecode,\n"
"    uint expr_bytecode_size,\n"
"    __global const gpu_multipart_tracker_t *trackers,\n"
"    uint num_trackers,\n"
"    uint file_length,\n"
"    uint entry_point,\n"
"    uint num_sections,\n"
"    uint container_type,\n"
"    __global const uint *intermediates_types,\n"
"    uint num_intermediates,\n"
"    uint is_pe_target,\n"
"    __global const uchar *icon_data,\n"
"    uint icon_data_size,\n"
"    volatile __global gpu_scan_result_t *result,\n"
"    __global const char *virname_pool)\n"
"{\n"
"    uint gid = get_global_id(0);\n"
"    if (gid >= num_lsigs) return;\n"
"    if (result->result_code == GPU_RESULT_VIRUS) return;\n"
"    \n"
"    __global const gpu_lsig_meta_t *meta = &lsig_metas[gid];\n"
"    if (gid < 10) {\n"
"        printf(\"LSIG[%u]: Starting, result_code=%d\\n\", gid, result->result_code);\n"
"    }\n"

"    \n"
"    /* Always print for our test signatures (virname_offset will be non-zero) */\n"

"    \n"
"    /* Find tracker for this logical signature */\n"
"    __global const gpu_multipart_tracker_t *tracker = 0;\n"
"    for (uint t = 0; t < num_trackers; t++) {\n"
"        if (trackers[t].sig_id == meta->sig_id) {\n"
"            tracker = &trackers[t];\n"
"    if (meta->virname_offset == 268977 && tracker) {\n"
"        printf(\"SUSPECT LSIG[%u]: subsig counts: \", gid);\n"
"        for (uint s = 0; s < meta->num_subsigs && s < 16; s++) {\n"
"            printf(\"%u=%u \", s, tracker->subsig_counts[s]);\n"
"        }\n"
"        printf(\"\\n\");\n"
"    }\n"
"            if (meta->virname_offset != 0) {\n"
"                printf(\"LSIG[%u]: Found tracker with mask=0x%x\\n\",\n"
"                       gid, tracker->found_mask_lo);\n"
"                /* Print subsig counts */\n"
"                for (uint s = 0; s < meta->num_subsigs && s < 16; s++) {\n"
// "                    if (tracker->subsig_counts[s] > 0) {\n"
// "                        printf(\"LSIG[%u]: subsig[%u] count=%u\\n\",\n"
// "                               gid, s, tracker->subsig_counts[s]);\n"
// "                    }\n"
"                }\n"
"            }\n"
"            break;\n"
"        }\n"
"    }\n"
"    \n"
"    if (tracker) {\n"
"        printf(\"LSIG[%u]: Tracker found for sig_id=%u, mask=0x%x\\n\",\n"
"               gid, meta->sig_id, tracker->found_mask_lo);\n"
"        for (uint s = 0; s < meta->num_subsigs && s < 16; s++) {\n"
// "            if (tracker->subsig_counts[s] > 0) {\n"
// "                printf(\"LSIG[%u]: subsig[%u] count=%u\\n\",\n"
// "                       gid, s, tracker->subsig_counts[s]);\n"
// "            }\n"
"        }\n"
"    }\n"
"    if (!tracker) {\n"
// "        if (meta->virname_offset != 0) {\n"
// "            printf(\"LSIG[%u]: No tracker found - no matches for this signature\\n\", gid);\n"
// "        }\n"
"        return;\n"
"    }\n"
"    \n"
"    /* Two-stack machine for count operations */\n"
"    uint count_stack[16];\n"
"    uint mask_stack[16];\n"
"    uint sp = 0;\n"
"    uint pc = meta->expr_offset;\n"
"    uint end_pc = pc + meta->expr_length;\n"
"    \n"
"    /* Safety check for bytecode bounds */\n"
"    if (end_pc > expr_bytecode_size) {\n"
"        end_pc = expr_bytecode_size;\n"
"    }\n"
"    \n"
"    while (pc < end_pc) {\n"
"        uint op = expr_bytecode[pc].op;\n"
"        uint operand = expr_bytecode[pc].operand;\n"
"        pc++;\n"
"        \n"
// "        if (meta->virname_offset != 0) {\n"
// "            printf(\"LSIG[%u]: op=%u, operand=%u, sp=%u\\n\", gid, op, operand, sp);\n"
// "        }\n"
"        \n"
"        switch (op) {\n"
"            case OP_LOAD_SUBSIG: /* 0 - LOAD subsig as boolean */\n"
"                if (result->result_code == GPU_RESULT_VIRUS) return;\n"
"                if (operand < meta->num_subsigs) {\n"
"                    uint val = (tracker->subsig_counts[operand] > 0) ? 1 : 0;\n"
"                    if (sp < 16) {\n"
"                        count_stack[sp] = val;\n"
"                        mask_stack[sp] = (val) ? (1u << operand) : 0;\n"
"                        sp++;\n"
// "                        if (meta->virname_offset != 0) {\n"
// "                            printf(\"LSIG[%u]: LOAD_SUBSIG[%u] = %u (count=%u)\\n\",\n"
// "                                   gid, operand, val, tracker->subsig_counts[operand]);\n"
// "                        }\n"
"                    }\n"
"                }\n"
"                break;\n"
"\n"
"            case OP_LOAD_COUNT: /* 5 - LOAD actual count */\n"
"                if (operand < meta->num_subsigs) {\n"
"                    uint count = tracker->subsig_counts[operand];\n"
"                    if (sp < 16) {\n"
"                        count_stack[sp] = count;\n"
"                        mask_stack[sp] = (count > 0) ? (1u << operand) : 0;\n"
"                        sp++;\n"
"                        if (meta->virname_offset != 0) {\n"
"                            printf(\"LSIG[%u]: LOAD_COUNT[%u] = %u\\n\",\n"
"                                   gid, operand, count);\n"
"                        }\n"
"                    }\n"
"                }\n"
"                break;\n"
"\n"
"            case OP_GT: /* 7 - Compare count > value */\n"
"                if (sp >= 1) {\n"
"                    uint val = operand;\n"
"                    uint count = count_stack[sp-1];\n"
"                    count_stack[sp-1] = (count > val) ? 1 : 0;\n"
// "                    if (meta->virname_offset != 0) {\n"
// "                        printf(\"LSIG[%u]: GT %u: count=%u -> %u\\n\",\n"
// "                               gid, val, count, count_stack[sp-1]);\n"
// "                    }\n"
"                }\n"
"                break;\n"
"\n"
"            case OP_AND: /* 1 - AND */\n"
"                if (sp >= 2) {\n"
"                    sp--;\n"
"                    uint b = count_stack[sp];\n"
"                    uint a = count_stack[sp-1];\n"
"                    count_stack[sp-1] = a && b;\n"
// "                    if (meta->virname_offset != 0) {\n"
// "                        printf(\"LSIG[%u]: AND %u && %u = %u\\n\",\n"
// "                               gid, a, b, count_stack[sp-1]);\n"
// "                    }\n"
"                }\n"
"                break;\n"
"\n"
"            case OP_OR: /* 2 - OR */\n"
"                if (sp >= 2) {\n"
"                    sp--;\n"
"                    uint b = count_stack[sp];\n"
"                    uint a = count_stack[sp-1];\n"
"                    count_stack[sp-1] = a || b;\n"
// "                    if (meta->virname_offset != 0) {\n"
// "                        printf(\"LSIG[%u]: OR %u || %u = %u\\n\",\n"
// "                               gid, a, b, count_stack[sp-1]);\n"
// "                    }\n"
"                }\n"
"                break;\n"
"\n"
"            case OP_END: /* 4 - END */\n"
"                if (sp >= 1) {\n"
"                    if (count_stack[0]) {\n"
"                        /* TDB validation */\n"
"                        if (meta->tdb_container && meta->tdb_container != container_type) {\n"
"                            return;\n"
"                        }\n"
"                        if (meta->tdb_filesize_max && \n"
"                            (file_length < meta->tdb_filesize_min || \n"
"                             file_length > meta->tdb_filesize_max)) {\n"
"                            return;\n"
"                        }\n"
"                        if (is_pe_target && meta->tdb_ep_max &&\n"
"                            (entry_point < meta->tdb_ep_min || entry_point > meta->tdb_ep_max)) {\n"
"                            return;\n"
"                        }\n"
"                        \n"
"                        /* Report virus */\n"
"                        int old = atomic_cmpxchg(&result->result_code, GPU_RESULT_CLEAN, GPU_RESULT_VIRUS);\n"
"                        if (old == GPU_RESULT_CLEAN) {\n"
"                            result->virname_offset = meta->virname_offset;\n"
"                            result->virname_len = meta->virname_len;\n"
"                        }\n"
"                    }\n"
"                }\n"
"                return;\n"
"        }\n"
"    }\n"
"}\n"
#endif /* GPU_AC_KERNEL_H */